name: mobileshop_pos
description: "Mobile Parts Manager - Offline POS for mobile phone repair shops"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  pdf: ^3.10.8
  printing: ^5.12.0
  excel: ^4.0.2
  file_picker: ^8.0.3
  share_plus: ^9.0.0
  blue_thermal_printer: ^1.1.1
  intl: ^0.19.0
  path_provider: ^2.1.3
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
